events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen       80 default_server;
        server_name _;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location /search {
            proxy_pass http://middleware:8000/search;
        }

        location /docs {
            proxy_pass http://middleware:8000/docs;
        }

        location /openapi.json {
            proxy_pass http://middleware:8000/openapi.json;
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
}
